# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 726cf824005f8b542bdc80f7ae054ee0f32a620633acb71e3c304de6680d467e4acf4bb236a77a411264c22ce470854a85c4903818dd0ab73818739c865d0b4f

test:
  secret_key_base: d3bcb48b7923f44c9672979191b10ed26c1430f7834ce483f13feeaf842f145c46483f63f2d8288ae3eb7325a9006c9861a37781368037e2f5cd1724e024d90e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
